#!/bin/bash

# Setting up pacman.conf
nano /etc/pacman.conf

# Setting up timezone
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
hwclock --systohc

# Setting up locale
echo "LC_ALL=sv_SE.UTF-8" | tee -a /etc/environment
echo "sv_SE.UTF-8 UTF-8" | tee -a /etc/locale.gen
echo "LANG=sv_SE.UTF-8" | tee -a /etc/locale.conf
echo "KEYMAP=sv-latin1" | tee -a /etc/vconsole.conf
locale-gen

# Setting up /etc/hostname
echo "arch-laptop" | tee -a /etc/hostname
echo "127.0.0.1	localhost" | tee -a /etc/hosts
echo "::1		    localhost" | tee -a /etc/hosts
echo "127.0.1.1  arch-laptop" | tee -a /etc/hosts
echo "::1        localhost ip6-localhost ip6-loopback" | tee -a /etc/hosts
echo "ff02::1    ip6-allnodes" | tee -a /etc/hosts
echo "ff02::2    ip6-allrouters" | tee -a /etc/hosts

# Starting installation
pacman -Syy
pacman-key --populate archlinux
passwd

#temp string for testing
pacman -S --noconfirm efibootmgr xorg xorg-server gdm gnome networkmanager gedit gnome-tweaks gparted sudo fuse libreoffice-fresh-sv firefox vlc qbittorrent htop p7zip unrar unarchiver lzop lrzip git fish wine wine-gecko wine-mono winetricks lutris steam nvidia nvidia-settings nvidia-utils lib32-nvidia-utils opencl-nvidia lib32-opencl-nvidia vulkan-icd-loader lib32-vulkan-icd-loader libvdpau libxnvctrl

# Preparing boot partition and installing systemd-boot
bootctl --path=/boot install
echo "default arch*" | tee /boot/loader/loader.conf
echo "title Arch Linux" | tee -a /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux" | tee -a /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux.img" | tee -a /boot/loader/entries/arch.conf
echo "options root=/dev/sda1 rw" | tee -a /boot/loader/entries/arch.conf

# Enabling Services and adding accounts
systemctl enable gdm.service
systemctl enable NetworkManager.service
useradd -m modda
passwd modda
xdg-user-dirs-update
EDITOR=nano visudo
mv /user /home/modda/user
cd /home/modda
su modda
