#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

# Mounting root partition
mount /dev/sda2 /mnt

mkdir /mnt/boot
mount /dev/sda1 /mnt/boot


# Installing base system
pacstrap /mnt base base-devel linux linux-firmware nano

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv install /mnt
mv user /mnt

# Chroot into new system
arch-chroot /mnt
